global:
  scrape_interval:     10s
  evaluation_interval: 10s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'docker-host-alpha'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
# rule_files:
#   - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['nodeexporter:9100']

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: goods-scanner-api
    scrape_interval: 10s
    static_configs:
    - targets: ['goods-scanner-api:8081']
  - job_name: caddy
    static_configs:
      - targets: ['caddy:2019']
  
  # - job_name: 'cadvisor'
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets: ['cadvisor:8080']

  # - job_name: 'pushgateway'
  #   scrape_interval: 10s
  #   honor_labels: true
  #   static_configs:
  #     - targets: ['pushgateway:9091']